# Generated by Django 4.2.1 on 2023-09-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pro_ID', models.CharField(max_length=50)),
                ('Pro_Name', models.CharField(max_length=30)),
                ('Pro_Price', models.CharField(max_length=25)),
                ('Rating', models.IntegerField()),
            ],
        ),
    ]
